package com.sun.swing.internal.plaf.basic.resources;

import java.util.ListResourceBundle;

public final class basic_ru extends ListResourceBundle {

    public basic_ru() {
    }

    @Override
    protected final Object[][] getContents() {
        return (new Object[][] { new Object[] { "AbstractButton.clickText", "клик" },
            new Object[] { "AbstractDocument.additionText", "добавление" },
            new Object[] { "AbstractDocument.deletionText", "удаление" },
            new Object[] { "AbstractDocument.redoText", "Повторить" },
            new Object[] { "AbstractDocument.styleChangeText", "смену стиля" },
            new Object[] { "AbstractDocument.undoText", "Отменить" },
            new Object[] { "AbstractUndoableEdit.redoText", "Повторить" },
            new Object[] { "AbstractUndoableEdit.undoText", "Отменить" },
            new Object[] { "ColorChooser.cancelText", "Отмена" }, new Object[] { "ColorChooser.hsbBlueText", "B" },
            new Object[] { "ColorChooser.hsbBrightnessText", "Яркость" },
            new Object[] { "ColorChooser.hsbDisplayedMnemonicIndex", "0" },
            new Object[] { "ColorChooser.hsbGreenText", "G" }, new Object[] { "ColorChooser.hsbHueText", "Оттенок" },
            new Object[] { "ColorChooser.hsbMnemonic", "72" }, new Object[] { "ColorChooser.hsbNameText", "HSB" },
            new Object[] { "ColorChooser.hsbRedText", "R" },
            new Object[] { "ColorChooser.hsbSaturationText", "Насыщенность" },
            new Object[] { "ColorChooser.okText", "OK" }, new Object[] { "ColorChooser.previewText", "Просмотр" },
            new Object[] { "ColorChooser.resetMnemonic", "82" }, new Object[] { "ColorChooser.resetText", "Сброс" },
            new Object[] { "ColorChooser.rgbBlueMnemonic", "66" },
            new Object[] { "ColorChooser.rgbBlueText", "Синий" },
            new Object[] { "ColorChooser.rgbDisplayedMnemonicIndex", "1" },
            new Object[] { "ColorChooser.rgbGreenMnemonic", "78" },
            new Object[] { "ColorChooser.rgbGreenText", "Зеленый" }, new Object[] { "ColorChooser.rgbMnemonic", "71" },
            new Object[] { "ColorChooser.rgbNameText", "RGB" }, new Object[] { "ColorChooser.rgbRedMnemonic", "68" },
            new Object[] { "ColorChooser.rgbRedText", "Красный" },
            new Object[] { "ColorChooser.sampleText", "Пример текста  Пример текста" },
            new Object[] { "ColorChooser.swatchesDisplayedMnemonicIndex", "0" },
            new Object[] { "ColorChooser.swatchesMnemonic", "83" },
            new Object[] { "ColorChooser.swatchesNameText", "Палитра" },
            new Object[] { "ColorChooser.swatchesRecentText", "Последние:" },
            new Object[] { "ComboBox.togglePopupText", "Раскрыть список" },
            new Object[] { "FileChooser.acceptAllFileFilterText", "Все файлы" },
            new Object[] { "FileChooser.cancelButtonMnemonic", "67" },
            new Object[] { "FileChooser.cancelButtonText", "Отмена" },
            new Object[] { "FileChooser.cancelButtonToolTipText", "Закрыть диалог" },
            new Object[] { "FileChooser.directoryDescriptionText", "Папка" },
            new Object[] { "FileChooser.directoryOpenButtonMnemonic", "79" },
            new Object[] { "FileChooser.directoryOpenButtonText", "Открыть" },
            new Object[] { "FileChooser.directoryOpenButtonToolTipText", "Открыть выбранную директорию" },
            new Object[] { "FileChooser.fileDescriptionText", "Все файлы" },
            new Object[] { "FileChooser.fileSizeGigaBytes", "{0} GB" },
            new Object[] { "FileChooser.fileSizeKiloBytes", "{0} KB" },
            new Object[] { "FileChooser.fileSizeMegaBytes", "{0} MB" },
            new Object[] { "FileChooser.helpButtonMnemonic", "72" },
            new Object[] { "FileChooser.helpButtonText", "Помощь" },
            new Object[] { "FileChooser.helpButtonToolTipText", "Показать справку" },
            new Object[] { "FileChooser.newFolderErrorSeparator", ": " },
            new Object[] { "FileChooser.newFolderErrorText", "Ошибка при создании каталога" },
            new Object[] { "FileChooser.openButtonMnemonic", "79" },
            new Object[] { "FileChooser.openButtonText", "Открыть" },
            new Object[] { "FileChooser.openButtonToolTipText", "Открыть выбранный файл" },
            new Object[] { "FileChooser.openDialogTitleText", "Открыть" },
            new Object[] { "FileChooser.other.newFolder", "Новая папка" },
            new Object[] { "FileChooser.other.newFolder.subsequent", "Новая папка.{0}" },
            new Object[] { "FileChooser.saveButtonMnemonic", "83" },
            new Object[] { "FileChooser.saveButtonText", "Сохранить" },
            new Object[] { "FileChooser.saveButtonToolTipText", "Сохранить выбранный файл" },
            new Object[] { "FileChooser.saveDialogTitleText", "Сохранить" },
            new Object[] { "FileChooser.updateButtonMnemonic", "85" },
            new Object[] { "FileChooser.updateButtonText", "Обновить" },
            new Object[] { "FileChooser.updateButtonToolTipText", "Обновить список директорий" },
            new Object[] { "FileChooser.win32.newFolder", "Новая папка" },
            new Object[] { "FileChooser.win32.newFolder.subsequent", "Новая папка ({0})" },
            new Object[] { "FormView.browseFileButtonText", "Просмотр..." },
            new Object[] { "FormView.resetButtonText", "Сброс" },
            new Object[] { "FormView.submitButtonText", "Отправить запрос" },
            new Object[] { "InternalFrame.closeButtonToolTip", "Закрыть" },
            new Object[] { "InternalFrame.iconButtonToolTip", "Свернуть" },
            new Object[] { "InternalFrame.maxButtonToolTip", "Развернуть" },
            new Object[] { "InternalFrame.restoreButtonToolTip", "Восстановить" },
            new Object[] { "InternalFrameTitlePane.closeButtonAccessibleName", "Закрыть" },
            new Object[] { "InternalFrameTitlePane.closeButtonText", "Закрыть" },
            new Object[] { "InternalFrameTitlePane.iconifyButtonAccessibleName", "Свернуть" },
            new Object[] { "InternalFrameTitlePane.maximizeButtonAccessibleName", "Развернуть" },
            new Object[] { "InternalFrameTitlePane.maximizeButtonText", "Развернуть" },
            new Object[] { "InternalFrameTitlePane.minimizeButtonText", "Свернуть" },
            new Object[] { "InternalFrameTitlePane.moveButtonText", "Переместить" },
            new Object[] { "InternalFrameTitlePane.restoreButtonText", "Восстановить" },
            new Object[] { "InternalFrameTitlePane.sizeButtonText", "Размер" },
            new Object[] { "IsindexView.prompt", "Индексированный поиск.  Введите ключевые слова:" },
            new Object[] { "OptionPane.cancelButtonMnemonic", "0" },
            new Object[] { "OptionPane.cancelButtonText", "Отмена" },
            new Object[] { "OptionPane.inputDialogTitle", "Ввод" },
            new Object[] { "OptionPane.messageDialogTitle", "Сообщение" },
            new Object[] { "OptionPane.noButtonMnemonic", "78" }, new Object[] { "OptionPane.noButtonText", "Нет" },
            new Object[] { "OptionPane.okButtonMnemonic", "0" }, new Object[] { "OptionPane.okButtonText", "OK" },
            new Object[] { "OptionPane.titleText", "Выберите значение" },
            new Object[] { "OptionPane.yesButtonMnemonic", "89" }, new Object[] { "OptionPane.yesButtonText", "Да" },
            new Object[] { "PrintingDialog.abortButtonDisplayedMnemonicIndex", "0" },
            new Object[] { "PrintingDialog.abortButtonMnemonic", "65" },
            new Object[] { "PrintingDialog.abortButtonText", "Прервать" },
            new Object[] { "PrintingDialog.abortButtonToolTipText", "Прервать печать" },
            new Object[] { "PrintingDialog.contentAbortingText", "Прерывание печати..." },
            new Object[] { "PrintingDialog.contentInitialText", "Идет печать..." },
            new Object[] { "PrintingDialog.contentProgressText", "Печатается страница {0}..." },
            new Object[] { "PrintingDialog.titleAbortingText", "Печать (прерывание)" },
            new Object[] { "PrintingDialog.titleProgressText", "Печать" },
            new Object[] { "ProgressMonitor.progressText", "Процесс..." },
            new Object[] { "SplitPane.leftButtonText", "левая кнопка" },
            new Object[] { "SplitPane.rightButtonText", "правая кнопка" } });
    }
}
