/*
 * Copyright (c) 2026 Weasis Team and other contributors.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse
 * Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0, or the Apache
 * License, Version 2.0 which is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
 */
package org.weasis.dicom.codec;

import java.awt.geom.Rectangle2D;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Locale;
import org.weasis.core.api.media.data.AnonymizationAction;
import org.weasis.core.api.media.data.MaskRegion;
import org.weasis.core.api.media.data.MaskingProfile;
import org.weasis.core.api.media.data.PixelMask;
import org.weasis.core.api.media.data.PixelMask.DeviceKey;
import org.weasis.core.api.media.data.PixelMask.Reference;
import org.weasis.core.api.media.data.TagCategory;
import org.weasis.core.util.StringUtil;

/**
 * Converts the pixel masks of the masking document to and from the {@code masks:} block of a Karnak
 * profile, where a mask is a station name, an optional image size and absolute rectangles.
 *
 * <p>The two models answer different questions, so a conversion loses something in each direction
 * and says what: Karnak matches on the station name only and takes rectangles, Weasis keys on more
 * attributes, keeps normalized regions of three shapes and a category per region. Above all, a
 * Weasis region hides pixels at display time while a Karnak mask overwrites them in the instances
 * the gateway forwards.
 */
public final class KarnakMasks {

  /** What a conversion could not carry over. */
  public record Loss(String maskId, String message) {}

  /** Default fill color, black; a null color makes Karnak blur the region instead. */
  public static final String BLACK = "000000"; // NON-NLS

  private static final String MASKS = "masks:"; // NON-NLS
  private static final String INDENT = "  "; // NON-NLS

  private KarnakMasks() {}

  /**
   * The {@code masks:} block for the regions {@code profile} hides, or a whole profile document
   * when {@code completeProfile}.
   *
   * @param color hexadecimal fill color, or null to let Karnak blur the regions
   * @param losses collects what the conversion dropped
   */
  public static String toYaml(
      Collection<PixelMask> masks,
      MaskingProfile profile,
      String color,
      boolean completeProfile,
      List<Loss> losses) {
    StringBuilder text = new StringBuilder();
    text.append("# Generated by Weasis from the masking profile '") // NON-NLS
        .append(profile.id())
        .append("' on ") // NON-NLS
        .append(LocalDate.now(ZoneId.systemDefault()))
        .append(System.lineSeparator())
        .append("# Karnak overwrites these pixels in the stored instances it forwards.") // NON-NLS
        .append(System.lineSeparator());
    if (completeProfile) {
      text.append(
          """
          name: "Weasis pixel masks"
          version: "1.0"
          minimumKarnakVersion: "0.9.2"
          profileElements:
            - name: "Clean pixel data"
              codename: "clean.pixel.data"
            - name: "DICOM basic profile"
              codename: "basic.dicom.profile"

          """);
    }
    text.append(MASKS).append(System.lineSeparator());
    int written = 0;
    for (PixelMask mask : masks) {
      written += appendMask(text, mask, profile, color, losses) ? 1 : 0;
    }
    if (written == 0) {
      losses.add(new Loss(null, "No mask could be converted"));
    }
    return text.toString();
  }

  public static void write(
      Path file,
      Collection<PixelMask> masks,
      MaskingProfile profile,
      String color,
      boolean completeProfile,
      List<Loss> losses)
      throws IOException {
    Files.writeString(
        file, toYaml(masks, profile, color, completeProfile, losses), StandardCharsets.UTF_8);
  }

  private static boolean appendMask(
      StringBuilder text, PixelMask mask, MaskingProfile profile, String color, List<Loss> losses) {
    if (!mask.enabled()) {
      return false;
    }
    DeviceKey key = mask.match();
    if (key.manufacturer() != null || key.modelName() != null || key.institutionName() != null) {
      // Karnak resolves on the station name alone: a wider rule would mask machines never checked
      losses.add(
          new Loss(
              mask.id(),
              "Keyed on manufacturer, model or institution, which Karnak cannot express"));
      return false;
    }
    List<String> rectangles = new ArrayList<>();
    for (MaskRegion region : mask.regions()) {
      if (profile.actionFor(region.category()) == AnonymizationAction.KEEP) {
        continue;
      }
      if (!(region instanceof MaskRegion.Rect)) {
        losses.add(
            new Loss(
                mask.id(), "A %s is exported as its bounding rectangle".formatted(region.kind())));
      }
      rectangles.add(rectangle(region, mask.reference()));
    }
    if (rectangles.isEmpty()) {
      losses.add(new Loss(mask.id(), "No region is hidden by this profile"));
      return false;
    }
    text.append(INDENT)
        .append("- stationName: \"") // NON-NLS
        .append(key.stationName() == null ? "*" : key.stationName())
        .append('"')
        .append(System.lineSeparator());
    appendField(text, "imageWidth", String.valueOf(mask.reference().columns())); // NON-NLS
    appendField(text, "imageHeight", String.valueOf(mask.reference().rows())); // NON-NLS
    if (StringUtil.hasText(color)) {
      appendField(text, "color", '"' + color + '"'); // NON-NLS
    }
    text.append(INDENT).append(INDENT).append("rectangles:").append(System.lineSeparator());
    for (String rectangle : rectangles) {
      text.append(INDENT.repeat(3))
          .append("- \"")
          .append(rectangle)
          .append('"')
          .append(System.lineSeparator());
    }
    return true;
  }

  private static void appendField(StringBuilder text, String name, String value) {
    text.append(INDENT)
        .append(INDENT)
        .append(name)
        .append(": ")
        .append(value)
        .append(System.lineSeparator());
  }

  /** The region as the absolute {@code x y w h} of the reference frame. */
  private static String rectangle(MaskRegion region, Reference reference) {
    Rectangle2D bounds = region.bounds();
    return "%d %d %d %d"
        .formatted(
            Math.round(bounds.getX() * reference.columns()),
            Math.round(bounds.getY() * reference.rows()),
            Math.max(1, Math.round(bounds.getWidth() * reference.columns())),
            Math.max(1, Math.round(bounds.getHeight() * reference.rows())));
  }

  /**
   * Reads the {@code masks:} block of a Karnak profile. Only that block is understood; the rest of
   * the document is ignored, and a line of the block that is not one of the known fields is refused
   * rather than guessed.
   *
   * @param fallback size used when an entry gives none, since an absolute rectangle cannot be
   *     normalized without one
   */
  public static List<PixelMask> read(Path file, Reference fallback) throws IOException {
    List<Entry> entries = new ArrayList<>();
    Entry entry = null;
    boolean inMasks = false;
    boolean inRectangles = false;
    int entryIndent = -1;
    int line = 0;
    for (String raw : Files.readAllLines(file, StandardCharsets.UTF_8)) {
      line++;
      String text = strip(raw);
      if (text.isEmpty()) {
        continue;
      }
      if (!inMasks) {
        inMasks = text.equals(MASKS);
        continue;
      }
      // A sequence item of the block may sit at column 0, so only a key there ends the block
      if (!raw.startsWith(" ") && !raw.startsWith("\t") && !text.startsWith("-")) {
        break; // the next top-level key ends the block
      }
      if (text.startsWith("- ") || text.equals("-")) {
        String rest = text.substring(1).trim();
        // Indentation tells a rectangle of the current entry from the next entry of the block
        if (inRectangles && indent(raw) > entryIndent) {
          entry.rectangles.add(unquote(rest));
          continue;
        }
        inRectangles = false;
        entryIndent = indent(raw);
        entry = new Entry();
        entries.add(entry);
        readField(entry, rest, file, line);
        continue;
      }
      if (text.equals("rectangles:")) { // NON-NLS
        inRectangles = true;
        continue;
      }
      inRectangles = false;
      readField(entry, text, file, line);
    }
    if (entries.isEmpty()) {
      throw new IOException("No Karnak mask in " + file);
    }
    List<PixelMask> masks = new ArrayList<>();
    for (int i = 0; i < entries.size(); i++) {
      masks.add(entries.get(i).toMask(fallback, i));
    }
    return List.copyOf(masks);
  }

  private static void readField(Entry entry, String text, Path file, int line) throws IOException {
    if (entry == null) {
      throw new IOException("Mask field outside an entry in %s line %d".formatted(file, line));
    }
    int colon = text.indexOf(':');
    if (colon < 0) {
      throw new IOException("Unexpected mask line in %s line %d".formatted(file, line));
    }
    String name = text.substring(0, colon).trim();
    String value = unquote(text.substring(colon + 1).trim());
    switch (name) {
      case "stationName" -> entry.stationName = value; // NON-NLS
      case "imageWidth" -> entry.columns = integer(value, file, line); // NON-NLS
      case "imageHeight" -> entry.rows = integer(value, file, line); // NON-NLS
      case "color" -> entry.color = value; // NON-NLS
      default ->
          throw new IOException(
              "Unknown mask field '%s' in %s line %d".formatted(name, file, line));
    }
  }

  private static int integer(String value, Path file, int line) throws IOException {
    try {
      return Integer.parseInt(value.trim());
    } catch (NumberFormatException e) {
      throw new IOException("Not a number in %s line %d".formatted(file, line), e);
    }
  }

  private static int indent(String line) {
    int i = 0;
    while (i < line.length() && (line.charAt(i) == ' ' || line.charAt(i) == '\t')) {
      i++;
    }
    return i;
  }

  private static String strip(String line) {
    int comment = line.indexOf('#');
    return (comment < 0 ? line : line.substring(0, comment)).trim();
  }

  private static String unquote(String value) {
    String text = value.trim();
    if (text.length() > 1
        && (text.startsWith("\"") && text.endsWith("\"")
            || text.startsWith("'") && text.endsWith("'"))) {
      return text.substring(1, text.length() - 1);
    }
    return text;
  }

  /** One entry being read; the mask is built once its fields and rectangles are known. */
  private static final class Entry {
    private String stationName;
    private String color;
    private int columns;
    private int rows;
    private final List<String> rectangles = new ArrayList<>();

    private PixelMask toMask(Reference fallback, int index) {
      Reference reference = columns > 0 && rows > 0 ? new Reference(columns, rows) : fallback;
      List<MaskRegion> regions = new ArrayList<>();
      for (String rectangle : rectangles) {
        String[] parts = rectangle.trim().split("[ ,]+");
        if (parts.length == 4) {
          try {
            double x = Double.parseDouble(parts[0]) / reference.columns();
            double y = Double.parseDouble(parts[1]) / reference.rows();
            double w = Double.parseDouble(parts[2]) / reference.columns();
            double h = Double.parseDouble(parts[3]) / reference.rows();
            regions.add(new MaskRegion.Rect(x, y, w, h, TagCategory.DIRECT_ID));
          } catch (NumberFormatException e) {
            // A rectangle that is not four numbers is skipped by the caller's validation
          }
        }
      }
      String station = "*".equals(stationName) ? null : stationName;
      String name =
          station == null
              ? "Karnak mask %d".formatted(index + 1) // NON-NLS
              : "Karnak %s".formatted(station); // NON-NLS
      return new PixelMask(
          "karnak-" + (station == null ? "any" : station.toLowerCase(Locale.ROOT)) + "-" + index,
          name,
          new DeviceKey(null, station, null, null, null),
          reference,
          regions,
          List.of(),
          !regions.isEmpty());
    }
  }
}
