<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>weasis-parent</artifactId>
    <groupId>org.weasis</groupId>
    <!--suppress MavenPropertyInParent -->
    <version>${revision}${changelist}</version>
    <relativePath>../weasis-parent/pom.xml</relativePath>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.weasis.core</groupId>
  <artifactId>weasis-core</artifactId>
  <name>Core [${project.artifactId}]</name>
  <packaging>jar</packaging>

  <properties>
    <xchart.version>4.0.4</xchart.version>
    <VectorGraphics2D.version>0.13</VectorGraphics2D.version>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-dependency</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <includeArtifactIds>xchart,VectorGraphics2D,jakarta.json-api,parsson,oshi-core-ffm,oshi-common</includeArtifactIds>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>biz.aQute.bnd</groupId>
        <artifactId>bnd-maven-plugin</artifactId>
        <configuration>
          <bnd>
            -includeresource.all: lib/=target/dependency/;lib:=true
            Import-Package: org.slf4j;version=!,ch.qos.logback.*;version=!,\
            !org.apache.commons.codec.binary;resolution:=optional,com.madgag.gif.fmsware;resolution:=optional,de.rototor.pdfbox.graphics2d;\
            resolution:=optional,org.apache.pdfbox.pdmodel.*;resolution:=optional,org.scilab.forge.jlatexmath.*;resolution:=optional,\
            org.glassfish.hk2.osgiresourcelocator;resolution:=optional,\
            org.jspecify.annotations;resolution:=optional,\
            !sun.swing,*
            Export-Package: !org.weasis.core.internal,!org.weasis.core.util,org.weasis.core.*
            -exportcontents: org.knowm.xchart.*,de.erichseifert.*,jakarta.json.*
          </bnd>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.weasis.launcher</groupId>
      <artifactId>weasis-launcher</artifactId>
      <version>${project.parent.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.felix</groupId>
      <artifactId>org.apache.felix.gogo.command</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.felix</groupId>
      <artifactId>org.apache.felix.gogo.shell</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.felix</groupId>
      <artifactId>org.apache.felix.gogo.runtime</artifactId>
    </dependency>
    <dependency>
      <groupId>org.weasis.thirdparty</groupId>
      <artifactId>jaxb-osgi</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.json</groupId>
      <artifactId>jakarta.json-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.parsson</groupId>
      <artifactId>parsson</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.weasis.thirdparty</groupId>
      <artifactId>docking-frames</artifactId>
    </dependency>
    <dependency>
      <groupId>com.github.oshi</groupId>
      <artifactId>oshi-core-ffm</artifactId>
    </dependency>
    <dependency>
      <groupId>org.knowm.xchart</groupId>
      <artifactId>xchart</artifactId>
      <version>${xchart.version}</version>
      <exclusions>
        <exclusion>
          <groupId>com.madgag</groupId>
          <artifactId>animated-gif-lib</artifactId>
        </exclusion>
        <exclusion>
          <groupId>de.rototor.pdfbox</groupId>
          <artifactId>graphics2d</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>de.erichseifert.vectorgraphics2d</groupId>
      <artifactId>VectorGraphics2D</artifactId>
      <version>${VectorGraphics2D.version}</version>
    </dependency>
  </dependencies>
</project>
