package org.weasis.dicom.codec.enums;

/**
 * Official DICOM list of body part examinated. See also :
 * http://dicom.nema.org/MEDICAL/DICOM/current/output/chtml/part16/chapter_L.html
 *
 * @author Yannick LARVOR (ylarvor@smartwavesa.com)
 * @version 2.5.0
 * @since 2.5.0 - 2016-07-19 - ylar - Creation
 */
public enum BodyPartExaminated {
    ABDOMEN, ABDOMENPELVIS, ADRENAL, ANKLE, AORTA, ARM, AXILLA, BACK, BLADDER, BRAIN, BREAST, BRONCHUS, BUTTOCK,
    CALCANEUS, CALF, CAROTID, CEREBELLUM, CERVIX, CHEEK, CHEST, CHESTABDOMEN, CHESTABDPELVIS, CIRCLEOFWILLIS, CLAVICLE,
    COCCYX, COLON, CORNEA, CORONARYARTERY, CSPINE, CTSPINE, DUODENUM, EAR, ELBOW, ESOPHAGUS, EXTREMITY, EYE, EYELID,
    FACE, FEMUR, FINGER, FOOT, GALLBLADDER, HAND, HEAD, HEADNECK, HEART, HIP, HUMERUS, IAC, ILEUM, ILIUM, JAW, JEJUNUM,
    KIDNEY, KNEE, LARYNX, LEG, LIVER, LSPINE, LSSPINE, LUNG, MAXILLA, MEDIASTINUM, MOUTH, NECK, NECKCHEST,
    NECKCHESTABDOMEN, NECKCHESTABDPELV, NOSE, ORBIT, OVARY, PANCREAS, PAROTID, PATELLA, PELVIS, PENIS, PHARYNX,
    PROSTATE, RADIUS, RADIUSULNA, RECTUM, RIB, SCALP, SCAPULA, SCLERA, SCROTUM, SHOULDER, SKULL, SPINE, SPLEEN, SSPINE,
    STERNUM, STOMACH, SUBMANDIBULAR, TESTIS, THIGH, THUMB, THYMUS, THYROID, TIBIA, TIBIAFIBULA, TLSPINE, TMJ, TOE,
    TONGUE, TRACHEA, TSPINE, ULNA, URETER, URETHRA, UTERUS, VAGINA, VULVA, WHOLEBODY, WRIST, ZYGOMA;
}
