package org.weasis.dicom.codec.enums;

/**
 * Official DICOM list of body part examinated. See also :
 * http://dicom.nema.org/MEDICAL/DICOM/current/output/chtml/part16/chapter_L.html
 *
 * @author Yannick LARVOR (ylarvor@smartwavesa.com)
 * @version 2.5.0
 * @since 2.5.0 - 2016-07-19 - ylar - Creation
 */
public enum BodyPartExaminated {
    ABDOMEN, ABDOMENPELVIS, ADRENAL, ANKLE, AORTA, AXILLA, BACK, BLADDER, BRAIN, BREAST, BRONCHUS, BUTTOCK, CALCANEUS,
    CALF, CAROTID, CEREBELLUM, CSPINE, CTSPINE, CERVIX, CHEEK, CHEST, CHESTABDOMEN, CHESTABDPELVIS, CIRCLEOFWILLIS,
    CLAVICLE, COCCYX, COLON, CORNEA, CORONARYARTERY, DUODENUM, EAR, ELBOW, WHOLEBODY, ESOPHAGUS, EXTREMITY, EYE, EYELID,
    FACE, FEMUR, FINGER, FOOT, GALLBLADDER, HAND, HEAD, HEADNECK, HEART, HIP, HUMERUS, ILEUM, ILIUM, IAC, JAW, JEJUNUM,
    KIDNEY, KNEE, LARYNX, LIVER, LEG, LSPINE, LSSPINE, LUNG, MAXILLA, MEDIASTINUM, MOUTH, NECK, NECKCHEST,
    NECKCHESTABDOMEN, NECKCHESTABDPELV, NOSE, ORBIT, OVARY, PANCREAS, PAROTID, PATELLA, PELVIS, PENIS, PHARYNX,
    PROSTATE, RADIUS, RADIUSULNA, RECTUM, RIB, SSPINE, SCALP, SCAPULA, SCLERA, SCROTUM, SHOULDER, SKULL, SPINE, SPLEEN,
    STERNUM, STOMACH, SUBMANDIBULAR, TMJ, TESTIS, THIGH, TSPINE, TLSPINE, THUMB, THYMUS, THYROID, TIBIA, TIBIAFIBULA,
    TOE, TONGUE, TRACHEA, ULNA, ARM, URETER, URETHRA, UTERUS, VAGINA, VULVA, WRIST, ZYGOMA;
}
