#!/bin/sh
# postinst script for APPLICATION_PACKAGE
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
DESKTOP_COMMANDS_INSTALL
	    mkdir -p /etc/opt/chrome/policies/managed/
	    echo '{
    "URLWhitelist": ["weasis://*"]
}' > /etc/opt/chrome/policies/managed/weasis.json 
	    mkdir -p /etc/chromium/policies/managed/
	    cp /etc/opt/chrome/policies/managed/weasis.json /etc/chromium/policies/managed/weasis.json
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
