#!/bin/sh
# prerm script for APPLICATION_PACKAGE
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


UTILITY_SCRIPTS

case "$1" in
    remove|upgrade|deconfigure)
DESKTOP_COMMANDS_UNINSTALL
      uninstall_default_mime_handler weasis-Weasis.desktop x-scheme-handler/weasis
	    rm -f /etc/opt/chrome/policies/managed/weasis.json
	    rm -f /etc/chromium/policies/managed/weasis.json
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

