/*******************************************************************************
 * Copyright (c) 2011 Weasis Team.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Marcelo Porto - initial API and implementation, Animati Sistemas de Informática Ltda. (http://www.animati.com.br)
 *     
 ******************************************************************************/

package org.weasis.dicom.explorer.print;

import java.awt.Window;
import java.awt.image.BufferedImage;

import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

import org.weasis.core.api.gui.util.JMVUtils;
import org.weasis.core.api.gui.util.WinUtil;
import org.weasis.core.ui.editor.image.ExportImage;
import org.weasis.core.ui.editor.image.ImageViewerEventManager;
import org.weasis.core.ui.util.PrintOptions;

/**
 * 
 * @author Marcelo Porto (marcelo@animati.com.br)
 */
public class DicomPrintDialog extends javax.swing.JDialog {
    private javax.swing.JButton addPrinterButton;
    private javax.swing.JComboBox borderDensityComboBox;
    private javax.swing.JLabel borderDensityLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox colorPrintCheckBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JComboBox filmDestinationComboBox;
    private javax.swing.JLabel filmDestinationLabel;
    private javax.swing.JComboBox filmOrientationComboBox;
    private javax.swing.JLabel filmOrientationLabel;
    private javax.swing.JComboBox filmSizeIdComboBox;
    private javax.swing.JLabel filmSizeIdLabel;
    private javax.swing.JComboBox imageDisplayFormatComboBox;
    private javax.swing.JLabel imageDisplayLabel;
    private javax.swing.JComboBox magnificationTypeComboBox;
    private javax.swing.JLabel magnificationTypeLabel;
    private javax.swing.JLabel maxDensityLabel;
    private javax.swing.JSpinner maxDensitySpinner;
    private javax.swing.JComboBox mediumTypeComboBox;
    private javax.swing.JLabel mediumTypeLabel;
    private javax.swing.JLabel minDensityLabel;
    private javax.swing.JSpinner minDensitySpinner;
    private javax.swing.JLabel numOfCopiesLabel;
    private javax.swing.JSpinner numOfCopiesSpinner;
    private javax.swing.JCheckBox printAnnotationsCheckBox;
    private javax.swing.JButton printButton;
    private javax.swing.JSeparator printOptionsSeparator;
    private javax.swing.JLabel printerLabel;
    private javax.swing.JComboBox printersComboBox;
    private javax.swing.JSeparator printersSeparator;
    private javax.swing.JComboBox priorityComboBox;
    private javax.swing.JLabel priorityLabel;
    private javax.swing.JComboBox smoothingTypeComboBox;
    private javax.swing.JLabel smoothingTypeLabel;
    private javax.swing.JComboBox trimComboBox;
    private javax.swing.JLabel trimLabel;
    private javax.swing.DefaultComboBoxModel portraitDisplayFormatsModel;
    private javax.swing.DefaultComboBoxModel landscapeDisplayFormatsModel;
    private ImageViewerEventManager eventManager;

    /** Creates new form DicomPrintDialog */
    public DicomPrintDialog(Window parent, String title, ImageViewerEventManager eventManager) {
        super(parent, ModalityType.APPLICATION_MODAL);
        portraitDisplayFormatsModel =
            new javax.swing.DefaultComboBoxModel(new String[] { "STANDARD\\1,1", "STANDARD\\1,2", "STANDARD\\2,2",
                "STANDARD\\2,3", "STANDARD\\3,3", "STANDARD\\3,4", "STANDARD\\3,5", "STANDARD\\4,4", "STANDARD\\4,5",
                "STANDARD\\4,6" });

        landscapeDisplayFormatsModel =
            new javax.swing.DefaultComboBoxModel(new String[] { "STANDARD\\1,1", "STANDARD\\2,1", "STANDARD\\2,2",
                "STANDARD\\3,2", "STANDARD\\3,3", "STANDARD\\4,3", "STANDARD\\5,3", "STANDARD\\4,4", "STANDARD\\5,4" });

        this.eventManager = eventManager;
        initComponents();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printerLabel = new javax.swing.JLabel();
        printersComboBox = new javax.swing.JComboBox();
        mediumTypeLabel = new javax.swing.JLabel();
        mediumTypeComboBox = new javax.swing.JComboBox();
        priorityLabel = new javax.swing.JLabel();
        priorityComboBox = new javax.swing.JComboBox();
        filmDestinationLabel = new javax.swing.JLabel();
        filmDestinationComboBox = new javax.swing.JComboBox();
        numOfCopiesLabel = new javax.swing.JLabel();
        numOfCopiesSpinner = new javax.swing.JSpinner(new SpinnerNumberModel(1, 1, 100, 1));
        printersSeparator = new javax.swing.JSeparator();
        printOptionsSeparator = new javax.swing.JSeparator();
        imageDisplayLabel = new javax.swing.JLabel();
        imageDisplayFormatComboBox = new javax.swing.JComboBox();
        filmSizeIdLabel = new javax.swing.JLabel();
        filmSizeIdComboBox = new javax.swing.JComboBox();
        filmOrientationLabel = new javax.swing.JLabel();
        filmOrientationComboBox = new javax.swing.JComboBox();
        magnificationTypeLabel = new javax.swing.JLabel();
        magnificationTypeComboBox = new javax.swing.JComboBox();
        smoothingTypeLabel = new javax.swing.JLabel();
        smoothingTypeComboBox = new javax.swing.JComboBox();
        borderDensityLabel = new javax.swing.JLabel();
        borderDensityComboBox = new javax.swing.JComboBox();
        minDensityLabel = new javax.swing.JLabel();
        minDensitySpinner = new javax.swing.JSpinner(new SpinnerNumberModel(0, 0, 300, 1));
        maxDensityLabel = new javax.swing.JLabel();
        maxDensitySpinner = new javax.swing.JSpinner(new SpinnerNumberModel(0, 0, 300, 1));
        trimLabel = new javax.swing.JLabel();
        trimComboBox = new javax.swing.JComboBox();
        printButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        addPrinterButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        colorPrintCheckBox = new javax.swing.JCheckBox();
        printAnnotationsCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        printerLabel.setText("Printer:");

        printersComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        DicomPrinter.loadPrintersSettings(printersComboBox);
        enableOrDisableColorPrint();
        printersComboBox.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printersComboBoxActionPerformed(evt);
            }
        });

        mediumTypeLabel.setText("Medium Type:");

        mediumTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BLUE FILM", "CLEAR FILM" }));

        priorityLabel.setText("Priority:");

        priorityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LOW", "MED", "HIGH" }));

        filmDestinationLabel.setText("Film Destination:");

        filmDestinationComboBox
            .setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MAGAZINE", "PROCESSOR" }));

        numOfCopiesLabel.setText("Num. of Copies:");

        imageDisplayLabel.setText("Image Display Format:");

        imageDisplayFormatComboBox.setModel(portraitDisplayFormatsModel);

        filmSizeIdLabel.setText("Film Size ID:");

        filmSizeIdComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8INX10IN", "11INX14IN",
            "14INX14IN", "14INX17IN" }));

        filmOrientationLabel.setText("Film Orientation:");

        filmOrientationComboBox
            .setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PORTRAIT", "LANDSCAPE" }));
        filmOrientationComboBox.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmOrientationComboBoxActionPerformed(evt);
            }
        });

        magnificationTypeLabel.setText("Maginification Type:");

        magnificationTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BILINEAR", "CUBIC",
            "NONE" }));

        smoothingTypeLabel.setText("Smoothing Type:");

        smoothingTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(
            new String[] { "MEDIUM", "SHARP", "SMOOTH" }));

        borderDensityLabel.setText("Border Density:");

        borderDensityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BLACK", "WHITE" }));

        minDensityLabel.setText("Min Density:");

        maxDensityLabel.setText("Max Density:");

        trimLabel.setText("Trim:");

        trimComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NO", "YES" }));

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        addPrinterButton.setText("Add new");
        addPrinterButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPrinterButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        colorPrintCheckBox.setText("Print in color");

        printAnnotationsCheckBox.setText("Print image with annotations");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout
            .setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                            layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(
                                    layout.createSequentialGroup().addComponent(printAnnotationsCheckBox)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(printersSeparator)
                                .addComponent(printOptionsSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(
                                    layout
                                        .createSequentialGroup()
                                        .addGroup(
                                            layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(
                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                    layout
                                                        .createSequentialGroup()
                                                        .addComponent(imageDisplayLabel)
                                                        .addPreferredGap(
                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(imageDisplayFormatComboBox,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(filmSizeIdLabel)
                                                        .addPreferredGap(
                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(filmSizeIdComboBox, 0,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(
                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                    layout
                                                        .createSequentialGroup()
                                                        .addGroup(
                                                            layout
                                                                .createParallelGroup(
                                                                    javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(
                                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                                    layout
                                                                        .createSequentialGroup()
                                                                        .addGroup(
                                                                            layout
                                                                                .createParallelGroup(
                                                                                    javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                    false)
                                                                                .addGroup(
                                                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                                                    layout
                                                                                        .createSequentialGroup()
                                                                                        .addComponent(
                                                                                            filmDestinationLabel)
                                                                                        .addPreferredGap(
                                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(
                                                                                            filmDestinationComboBox,
                                                                                            0,
                                                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                            Short.MAX_VALUE))
                                                                                .addGroup(
                                                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                                                    layout
                                                                                        .createSequentialGroup()
                                                                                        .addComponent(mediumTypeLabel)
                                                                                        .addPreferredGap(
                                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(
                                                                                            mediumTypeComboBox,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                            99,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGap(18, 18, 18)
                                                                        .addGroup(
                                                                            layout
                                                                                .createParallelGroup(
                                                                                    javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(
                                                                                    layout
                                                                                        .createSequentialGroup()
                                                                                        .addComponent(priorityLabel)
                                                                                        .addPreferredGap(
                                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(
                                                                                            priorityComboBox,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                            99,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(
                                                                                    layout
                                                                                        .createSequentialGroup()
                                                                                        .addComponent(numOfCopiesLabel)
                                                                                        .addPreferredGap(
                                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(
                                                                                            numOfCopiesSpinner,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                            52,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(
                                                                                            colorPrintCheckBox))))
                                                                .addGroup(
                                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                                    layout
                                                                        .createSequentialGroup()
                                                                        .addGroup(
                                                                            layout
                                                                                .createParallelGroup(
                                                                                    javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(
                                                                                    layout
                                                                                        .createSequentialGroup()
                                                                                        .addComponent(
                                                                                            filmOrientationLabel)
                                                                                        .addPreferredGap(
                                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(
                                                                                            filmOrientationComboBox,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                            100,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(
                                                                                    layout
                                                                                        .createSequentialGroup()
                                                                                        .addComponent(
                                                                                            smoothingTypeLabel)
                                                                                        .addPreferredGap(
                                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(
                                                                                            smoothingTypeComboBox,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                            98,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGap(18, 18, 18)
                                                                        .addGroup(
                                                                            layout
                                                                                .createParallelGroup(
                                                                                    javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(
                                                                                    layout
                                                                                        .createSequentialGroup()
                                                                                        .addComponent(
                                                                                            borderDensityLabel)
                                                                                        .addPreferredGap(
                                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(
                                                                                            borderDensityComboBox,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                            86,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(
                                                                                    layout
                                                                                        .createSequentialGroup()
                                                                                        .addComponent(
                                                                                            magnificationTypeLabel)
                                                                                        .addPreferredGap(
                                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(
                                                                                            magnificationTypeComboBox,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                            93,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGroup(
                                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                                    layout
                                                                        .createSequentialGroup()
                                                                        .addComponent(minDensityLabel)
                                                                        .addPreferredGap(
                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(minDensitySpinner,
                                                                            javax.swing.GroupLayout.PREFERRED_SIZE, 65,
                                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(maxDensityLabel)
                                                                        .addPreferredGap(
                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(maxDensitySpinner,
                                                                            javax.swing.GroupLayout.PREFERRED_SIZE, 66,
                                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addGroup(
                                                                            layout
                                                                                .createParallelGroup(
                                                                                    javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(
                                                                                    layout
                                                                                        .createSequentialGroup()
                                                                                        .addComponent(
                                                                                            printButton,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                            79,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(
                                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(
                                                                                            cancelButton,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                            79,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(
                                                                                    layout
                                                                                        .createSequentialGroup()
                                                                                        .addComponent(trimLabel)
                                                                                        .addPreferredGap(
                                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(
                                                                                            trimComboBox,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                            87,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGroup(
                                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                                    layout
                                                                        .createSequentialGroup()
                                                                        .addComponent(printerLabel)
                                                                        .addPreferredGap(
                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(printersComboBox,
                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                            221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(addPrinterButton)
                                                                        .addPreferredGap(
                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(editButton)
                                                                        .addPreferredGap(
                                                                            javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(deleteButton)))
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30,
                                            javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout
                .createSequentialGroup()
                .addContainerGap()
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(printerLabel)
                        .addComponent(printersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addPrinterButton).addComponent(editButton).addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printersSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mediumTypeLabel)
                        .addComponent(mediumTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(priorityLabel)
                        .addComponent(priorityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filmDestinationLabel)
                        .addComponent(filmDestinationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numOfCopiesLabel)
                        .addComponent(numOfCopiesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(colorPrintCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printOptionsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(imageDisplayLabel)
                        .addComponent(imageDisplayFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filmSizeIdLabel)
                        .addComponent(filmSizeIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filmOrientationLabel)
                        .addComponent(filmOrientationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(magnificationTypeLabel)
                        .addComponent(magnificationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(smoothingTypeLabel)
                        .addComponent(smoothingTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(borderDensityLabel)
                        .addComponent(borderDensityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minDensityLabel)
                        .addComponent(minDensitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maxDensityLabel)
                        .addComponent(maxDensitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(trimLabel)
                        .addComponent(trimComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(printAnnotationsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(printButton)
                        .addComponent(cancelButton)).addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filmOrientationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_filmOrientationComboBoxActionPerformed
        if (filmOrientationComboBox.getSelectedItem().equals("PORTRAIT")) {
            imageDisplayFormatComboBox.setModel(portraitDisplayFormatsModel);
        } else {
            imageDisplayFormatComboBox.setModel(landscapeDisplayFormatsModel);
        }
    }// GEN-LAST:event_filmOrientationComboBoxActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }// GEN-LAST:event_cancelButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_printButtonActionPerformed
        DicomPrintOptions dicomPrintOptions = new DicomPrintOptions();
        dicomPrintOptions.setMediumType((String) mediumTypeComboBox.getSelectedItem());
        dicomPrintOptions.setPriority((String) priorityComboBox.getSelectedItem());
        dicomPrintOptions.setFilmDestination((String) filmDestinationComboBox.getSelectedItem());
        dicomPrintOptions.setNumOfCopies((Integer) numOfCopiesSpinner.getValue());
        dicomPrintOptions.setImageDisplayFormat((String) imageDisplayFormatComboBox.getSelectedItem());
        dicomPrintOptions.setFilmSizeId((String) filmSizeIdComboBox.getSelectedItem());
        dicomPrintOptions.setFilmOrientation((String) filmOrientationComboBox.getSelectedItem());
        dicomPrintOptions.setMagnificationType((String) magnificationTypeComboBox.getSelectedItem());
        dicomPrintOptions.setSmoothingType((String) smoothingTypeComboBox.getSelectedItem());
        dicomPrintOptions.setBorderDensity((String) borderDensityComboBox.getSelectedItem());
        dicomPrintOptions.setMinDensity((Integer) minDensitySpinner.getValue());
        dicomPrintOptions.setMaxDensity((Integer) maxDensitySpinner.getValue());
        dicomPrintOptions.setTrim((String) trimComboBox.getSelectedItem());
        dicomPrintOptions.setPrintInColor(colorPrintCheckBox.isSelected());
        dicomPrintOptions.setDicomPrinter((DicomPrinter) printersComboBox.getSelectedItem());

        ExportImage exportImage = new ExportImage(eventManager.getSelectedViewPane());
        DicomPrint dicomPrint = new DicomPrint(dicomPrintOptions);
        BufferedImage image =
            DicomPrint.printImage(exportImage, new PrintOptions(printAnnotationsCheckBox.isSelected(), 1.0));
        try {
            dicomPrint.printImage(image);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unable to print the image.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        dispose();
    }// GEN-LAST:event_printButtonActionPerformed

    private void addPrinterButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addPrinterButtonActionPerformed
        Window parent = WinUtil.getParentWindow(this);
        PrinterDialog dialog = new PrinterDialog(parent, "", null, printersComboBox);
        JMVUtils.showCenterScreen(dialog);
        enableOrDisableColorPrint();
    }// GEN-LAST:event_addPrinterButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editButtonActionPerformed
        Window parent = WinUtil.getParentWindow(this);
        PrinterDialog dialog =
            new PrinterDialog(parent, "", (DicomPrinter) printersComboBox.getSelectedItem(), printersComboBox);
        JMVUtils.showCenterScreen(dialog);
        enableOrDisableColorPrint();
    }// GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteButtonActionPerformed
        printersComboBox.removeItemAt(printersComboBox.getSelectedIndex());
        DicomPrinter.savePrintersSettings(printersComboBox);
        enableOrDisableColorPrint();
    }// GEN-LAST:event_deleteButtonActionPerformed

    private void printersComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_printersComboBoxActionPerformed
        enableOrDisableColorPrint();
    }// GEN-LAST:event_printersComboBoxActionPerformed

    private void enableOrDisableColorPrint() {
        if (printersComboBox.getSelectedItem() != null) {
            DicomPrinter selectedPrinter = (DicomPrinter) printersComboBox.getSelectedItem();
            if (selectedPrinter.isColorPrintSupported()) {
                colorPrintCheckBox.setEnabled(true);
            } else {
                colorPrintCheckBox.setSelected(false);
                colorPrintCheckBox.setEnabled(false);
            }
        }
    }

}
