/*******************************************************************************
 * Copyright (c) 2011 Weasis Team.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Marcelo Porto - initial API and implementation, Animati Sistemas de Informática Ltda. (http://www.animati.com.br)
 *     
 ******************************************************************************/

package org.weasis.dicom.explorer.print;

import java.awt.Window;

/**
 * 
 * @author Marcelo Porto (marcelo@animati.com.br)
 */
public class PrinterDialog extends javax.swing.JDialog {
    private javax.swing.JLabel aeTitleLabel;
    private javax.swing.JTextField aeTitleTf;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox colorPrintSupportCheckBox;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTf;
    private javax.swing.JLabel hostnameLabel;
    private javax.swing.JTextField hostnameTf;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField portTf;
    private DicomPrinter dicomPrinter;
    private javax.swing.JComboBox printersComboBox;

    /**
     * Creates new form NewPrinterDialog
     */
    public PrinterDialog(Window parent, String title, DicomPrinter dicomPrinter, javax.swing.JComboBox printersComboBox) {
        super(parent, ModalityType.APPLICATION_MODAL);
        initComponents();
        this.dicomPrinter = dicomPrinter;
        this.printersComboBox = printersComboBox;
        if (dicomPrinter != null) {
            descriptionTf.setText(dicomPrinter.getDescription());
            aeTitleTf.setText(dicomPrinter.getAeTitle());
            hostnameTf.setText(dicomPrinter.getHostname());
            portTf.setText(dicomPrinter.getPort());
            colorPrintSupportCheckBox.setSelected(dicomPrinter.isColorPrintSupported());
        }
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descriptionLabel = new javax.swing.JLabel();
        descriptionTf = new javax.swing.JTextField();
        aeTitleLabel = new javax.swing.JLabel();
        aeTitleTf = new javax.swing.JTextField();
        hostnameLabel = new javax.swing.JLabel();
        hostnameTf = new javax.swing.JTextField();
        portLabel = new javax.swing.JLabel();
        portTf = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        colorPrintSupportCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        descriptionLabel.setText("Description:");

        aeTitleLabel.setText("AE title:");

        hostnameLabel.setText("Hostname:");

        portLabel.setText("Port:");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        colorPrintSupportCheckBox.setText("Color print supported");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout
                .createSequentialGroup()
                .addContainerGap()
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                            layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(
                                    layout
                                        .createSequentialGroup()
                                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(
                                    layout
                                        .createSequentialGroup()
                                        .addComponent(hostnameLabel)
                                        .addGap(177, 177, 177)
                                        .addComponent(portLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(portTf, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(
                            layout
                                .createSequentialGroup()
                                .addGroup(
                                    layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(
                                            javax.swing.GroupLayout.Alignment.TRAILING,
                                            layout.createSequentialGroup().addComponent(aeTitleLabel)
                                                .addGap(29, 29, 29))
                                        .addGroup(
                                            layout.createSequentialGroup().addComponent(descriptionLabel)
                                                .addGap(10, 10, 10)))
                                .addGroup(
                                    layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(descriptionTf, javax.swing.GroupLayout.DEFAULT_SIZE, 141,
                                            Short.MAX_VALUE)
                                        .addComponent(hostnameTf, javax.swing.GroupLayout.Alignment.LEADING,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                        .addComponent(aeTitleTf, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addComponent(colorPrintSupportCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout
                .createSequentialGroup()
                .addContainerGap()
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(descriptionLabel)
                        .addComponent(descriptionTf, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aeTitleTf, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aeTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                            layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hostnameLabel)
                                .addComponent(portLabel)
                                .addComponent(portTf, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(hostnameTf, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colorPrintSupportCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(okButton)
                        .addComponent(cancelButton)).addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }// GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okButtonActionPerformed
        if (dicomPrinter == null) {
            dicomPrinter = new DicomPrinter();
            dicomPrinter.setDescription(descriptionTf.getText());
            dicomPrinter.setAeTitle(aeTitleTf.getText());
            dicomPrinter.setHostname(hostnameTf.getText());
            dicomPrinter.setPort(portTf.getText());
            dicomPrinter.setColorPrintSupported(colorPrintSupportCheckBox.isSelected());
            printersComboBox.addItem(dicomPrinter);
        } else {
            dicomPrinter.setDescription(descriptionTf.getText());
            dicomPrinter.setAeTitle(aeTitleTf.getText());
            dicomPrinter.setHostname(hostnameTf.getText());
            dicomPrinter.setPort(portTf.getText());
            dicomPrinter.setColorPrintSupported(colorPrintSupportCheckBox.isSelected());
        }
        DicomPrinter.savePrintersSettings(printersComboBox);
        dispose();
    }// GEN-LAST:event_okButtonActionPerformed

}
