name: weasis
title: Weasis
base: core24
version: '4.7.0'
summary: A free/libre/open medical DICOM viewer
description: |
  Weasis is a multipurpose standalone and web-based DICOM viewer with 
  a highly modular architecture. It is a very popular clinical viewer 
  used in healthcare by hospitals, health networks, multicenter research 
  trials, and patients.
  
  Note: With Snap, the .weasis directory is now located in /home/<username>/snap/weasis/current/.
  
  Key features:
  - Flexible integration to PACS, VNA, RIS, HIS or PHR
  - Responsive user interface and work well on high DPI screens
  - Web access through weasis protocol
  - Multi-language support
  - Configuration of preferences on server-side and client-side
  - API for building custom plug-ins
  - DICOM Send (storeSCU and STOW-RS)
  - DICOM Query/Retrieve (C-GET, C-MOVE and WADO-URI) and DICOMweb (QUERY and RETRIEVE)
  - Dicomizer module (allow importing standard images and convert them in DICOM)
license: Apache-2.0
grade: stable
confinement: strict
platforms:
  amd64:
    build-on: [amd64]
  arm64:
    build-on: [arm64]

plugs:
  desktop:
    mount-host-font-cache: false
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  gnome-46-2404:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-46-2404
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

layout:
  /usr/bin/lpr:
    bind-file: $SNAP/usr/bin/lpr

parts:
  remote-openjdk:
    plugin: dump
    source:
      - on amd64: https://github.com/adoptium/temurin26-binaries/releases/download/jdk-26.0.1%2B8/OpenJDK26U-jdk_x64_linux_hotspot_26.0.1_8.tar.gz
      - on arm64: https://github.com/adoptium/temurin26-binaries/releases/download/jdk-26.0.1%2B8/OpenJDK26U-jdk_aarch64_linux_hotspot_26.0.1_8.tar.gz
    source-checksum:
      - on amd64: sha256/8e512f13e575a43655fc92319436c94890c137b9035cc6bd6f9cf24239704d3a
      - on arm64: sha256/613f9b2861dea937b24d5eca745ef8567733b377d0bb612195acaad0e3f61360
    organize:
      '*': java-runtime/
    override-stage: 'true'
    override-prime: 'true'

  remote-weasis-build:
    after: [remote-openjdk]
    plugin: dump
    stage-packages:
      - libc6
      - xdg-utils
      - zlib1g
      - libstdc++6
      - libgcc-s1
    #source: weasis-distributions/target/native-dist/weasis-native.zip
    source: https://github.com/nroduit/Weasis/releases/download/v4.7.0/weasis-native.zip
    source-checksum: sha256/bad1334c0ddfa1f381211879e83d37ae78621f573eab0edaff6e1adc217f4862
    organize:
      '*': weasis-native/
    override-stage: 'true'
    override-prime: 'true'

  weasis:
    after: [remote-weasis-build]
    plugin: nil
    source: .
    source-type: local
    source-subdir: weasis-distributions
    override-build: |
      echo "Preparing Weasis build environment..."
      WEASIS_REMOTE=$(echo ${CRAFT_PART_INSTALL} | sed 's|parts/weasis/|parts/remote-weasis-build/|g')
      WEASIS_JDK=$(echo ${CRAFT_PART_INSTALL} | sed 's|parts/weasis/|parts/remote-openjdk/|g')
      cp -Rf ${WEASIS_REMOTE}/weasis-native ${CRAFT_PART_BUILD}/
      weasis-native/build/script/package-weasis.sh --output ${CRAFT_PART_INSTALL} --no-installer --jdk ${WEASIS_JDK}/java-runtime
      mv ${CRAFT_PART_INSTALL}/Weasis/* ${CRAFT_PART_INSTALL}/
      rm -rf ${CRAFT_PART_INSTALL}/Weasis
      craftctl default

apps:
  weasis:
    extensions: [gnome]
    command: bin/Weasis
    environment:
      _JAVA_OPTIONS: -Duser.home=$SNAP_USER_DATA
    plugs:
      - network
      - desktop
      - x11
      - home
      - network-bind
      - gsettings
      - opengl
      - avahi-control
      - mount-observe
      - removable-media
      - cups-control
  
  dicomizer:
    extensions: [gnome]
    command: bin/Dicomizer
    environment:
      _JAVA_OPTIONS: -Duser.home=$SNAP_USER_DATA
    plugs:
      - network
      - desktop
      - x11
      - home
      - network-bind
      - gsettings
      - opengl
      - avahi-control
      - mount-observe
      - removable-media
      - cups-control
