name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    name: Build & Sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK for compilation
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '26'
          cache: 'maven'
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build with coverage
        run: mvn -Pcoverage -B -ntp verify

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: jacoco-aggregate
          path: tests/target/site/jacoco-aggregate/

      - name: Sonar analysis
        if: ${{ env.SONAR_TOKEN != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # Version is taken from <pluginManagement> in weasis-parent/pom.xml
        run: mvn -B -ntp sonar:sonar
